background:
  0:
    hidden: true
  1:
    hidden: true
  2:
    hidden: true
  3:
    hidden: true
  4:
    hidden: true
  5:
    hidden: true
  6:
    mirror: true
    mirror_hoffset: -18
terrain:
  1:
    hidden: true
  2: 
    mirror: true
    mirror_hoffset: 4
  3:
    mirror: true
    mirror_hoffset: -10
foreground: