background:
  0:
    hidden: true
  1:
    hidden: true
  2:
    hidden: true
  3:
    hidden: true
  vcenter: true
terrain:
  1:
    hidden: true
  2:
    mirror: true
    mirror_hoffset: 6