background: 
  0:
    hidden: true
  1: 
    hidden: true
  2: 
    hidden: true
  3: 
    hidden: true
  4: 
    hidden: true
  6: 
    mirror: true
    mirror_hoffset: 8
terrain: 
  2: 
    hidden: true
  3: 
    mirror: true
    mirror_hoffset: 2
foreground:
